name: Build 
on:
  pull_request:
    branches: [developement, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # adjust if you're on .NET 7, 6, etc.

      - name: Restore dependencies
        run: dotnet restore BackEnd/ChatQueue.API/ChatQueue.API.csproj

      - name: Build API project
        run: dotnet build BackEnd/ChatQueue.API/ChatQueue.API.csproj --no-restore --configuration Release
